---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deploymentname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    app.kubernetes.io/part-of: banking-platform
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      enableServiceLinks: false
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 300m
              memory: 128Mi
          readinessProbe:
            httpGet: { path: /, port: {{ .Values.frontend.port }} }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: {{ .Values.frontend.port }} }
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.servicename }}
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    app.kubernetes.io/part-of: banking-platform
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      {{- if eq .Values.frontend.serviceType "NodePort" }}
      nodePort: {{ .Values.frontend.nodePort }}
      {{- end }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.frontend.hpa }}
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.frontend.deploymentname }}
  minReplicas: {{ .Values.frontend.minReplicas }}
  maxReplicas: {{ .Values.frontend.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
